### PR TITLE
Use spark join to map dict on `DataFrameWrapper.data`

### PR DESCRIPTION
**Pull request by jamesgyoung**
Addresses #205.

Converts lookup dictionary to spark dataframe which can be joined to `.data` and the values extracted.
~259x faster (than previous `create_map` usage) for 3_000_000 rows/unique categories.

### CODE REVIEW

**Comment by jpd-defra** [comment]
Thanks for submitting this PR, it's looking good. I just gave it a spin on Databricks with the following dataset:

```
from sds_data_model.dataframe import DataFrameWrapper   

phi_sdf = DataFrameWrapper.from_files(name = 'pri_hab',
    data_path = '/dbfs/mnt/base/unrestricted/source_defra_data_services_platform',
    metadata_path = 'https://ckan.publishing.service.gov.uk/harvest/object/85e03bf0-4e95-4739-a5fa-21d60cf7f069',
    read_file_kwargs = {'pattern': 'dataset_priority_habitat_inventory_*/format_SHP_priority_habitat_inventory_*/LATEST_priority_habitat_inventory_*/PHI_v2_3_*',
    'suffix': '.shp',
    'ideal_chunk_size':1000})
```

First I tested a single column for categorisation:

```
phi_sdf.categorize(['Main_Habit'])
```

And the output looked as I would expect:

```
phi_sdf.lookup
```
```
Out[4]: {'Main_Habit': {'Deciduous woodland': 0,
  'Fragmented heath': 1,
  'Coastal sand dunes': 2,
  'Saline lagoons': 3,
  'Coastal vegetated shingle': 4,
  'Purple moor grass and rush pastures': 5,
  'Lowland dry acid grassland': 6,
  'Lowland meadows': 7,
  'Lowland fens': 8,
  'Coastal saltmarsh': 9,
  'Grass moorland': 10,
  'Limestone pavement': 11,
  'Lowland calcareous grassland': 12,
  'Mountain heaths and willow scrub': 13,
  'Good quality semi-improved grassland': 14,
  'Lowland raised bog': 15,
  'Upland heathland': 16,
  'Reedbeds': 17,
  'No main habitat but additional habitats present': 18,
  'Maritime cliff and slope': 19,
  'Lowland heathland': 20,
  'Upland calcareous grassland': 21,
  'Calaminarian grassland': 22,
  'Blanket bog': 23,
  'Traditional orchard': 24,
  'Upland hay meadow': 25,
  'Mudflats': 26,
  'Upland flushes, fens and swamps': 27,
  'Coastal and floodplain grazing marsh': 28}}
```

I then thought I would try with multiple columns:

```
phi_sdf.categorize(['Main_Habit','Source1'])
```

And I get a different output, but the `Main_Habit` names have been replaced with integers, and in a strange order, yet the `Source1` names are present in the lookup:

```
phi_sdf.lookup
```

```
Out[10]: {'Main_Habit': {26: 0,
  19: 1,
  0: 2,
  22: 3,
  7: 4,
  25: 5,
  6: 6,
  9: 7,
  27: 8,
  17: 9,
  28: 10,
  5: 11,
  1: 12,
  10: 13,
  3: 14,
  12: 15,
  8: 16,
  11: 17,
  2: 18,
  4: 19,
  13: 20,
  18: 21,
  14: 22,
  21: 23,
  15: 24,
  23: 25,
  20: 26,
  16: 27,
  24: 28},
 'Source1': {'English Nature Lowland Grassland Inventory': 0,
  'North Pennines AONB Partnership 2010': 1,
  'NZ0384': 2,
  'SE3860': 3,
  'SK8064': 4,
  'SE4317': 5,
  'SK4534': 6,
  'Engish Nature Humber to Pennines Team SSSI NVC Survey': 7,
  'Naddle Forest SSSI Habitat Survey': 8,
  'Hulme Park Phase 1': 9,
  'Waldridge Fell Habitat Survey map': 10,
  'SE4655': 11,
  'SE9302': 12,
  'The SBI Resurvey of East Staffordshire District': 13,
  'Derbyshire Calaminarian Grassland Project 2011': 14,
  'Trent Washlands Survey 2006': 15,
```

I see this as a problem with either:
a) Overwriting an existing lookup with a new lookup which contains the same column
b) An issue with providing multiple columns to `categorize`.

I guess my question is, does the method handle overwriting the lookup stored within `DataFrameWrapper`? If so, is it handling multiple columns as expected?

Do you have any thoughts/ideas?

**Comment by danlewis85** [comment]
> And I get a different output, but the Main_Habit names have been replaced with integers, and in a strange order, yet the Source1 names are present in the lookup

@JamesKeny0n can probably explain this one slightly better, but I found a similar thing when testing. In discuss with James, it appeared to result from some sort of larger issue with retained states. Basically, a work around would be to detach and reattach before trying to categorize again, and you should then see what you expected.

**Comment by jamesgyoung** [comment]
@jpd-defra The issue is that `categorize`  was called once on "Main_Habit" and  it worked, the underlying strings were mapped to ints. But you called `categorize` again on "Main_Habit", now you are mapping the underlying ints to new ints.
`categorize` works inplace.

**Comment by jpd-defra** [comment]
Thanks @danlewis85  and @JamesKeny0n. I've added a bit of detail to the `categorize` docstring and am happy to merge this branch once checks are satisfied.

**Pull request merged**
