### PR TITLE
Use on disk zarr and chunking to reshape data from `DatasetWrapper.from_files`.

### PR DESCRIPTION
**Pull request by jamesgyoung**
Addresses #198 by reworking the reshaping to resample on chunks of input rasters and dumping the chunk to a region of an empty zarr on disk, removing the need to position the array inside the full size grid in memory.

`_resample_and_reshape` has been replaced with new function `_reshape_raster`. This function is not broken down which might be the only issue, otherwise all tests that passed previously also do now.

### CODE REVIEW

**Comment by jpd-defra** [comment]
Hi James, good work on this. It's not an easy thing to crack, so I think you've done an admirable job. I have some comments below, which I feel should be addressed before merging:

**Usage**
1. When nothing is provided to the `chunks` argument in `DatasetWrapper.from_files()`, auto is used and a message is printed. This message doesn't come through in Databricks, and given this will be the primary place we intend to use the data model it would be good to make sure the user sees it. I used a [`warning`](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/b0cb3d1d8543285cdc0b9bb7110010b1433ebd10/src/sds_data_model/dataframe.py#L494) in `DataFrameWrapper.to_zarr`, which I know does print to the Databricks notebook... What is strange is that this `warning` isn't materialising for me. Any idea why?
1. In `DatasetWrapper.from_files()`, the `out_path` argument is shown as optional. However, when not providing a path, I get a FileNotFoundError.
2. What is the overwrite behaviour when an `out_path` is provided? I implemented a safety net in `DataFrameWrapper.to_zarr()`. I think we need something similar in place for `DatasetWrapper.from_files()`. Here's how I've implemented it:
    - the `overwrite` argument is set to `False` (default) and the user provides an empty directory to `out_path` = zarr written, no warning given.
    - the `overwrite` argument is set to `False` (default) and the user provides a directory containing a zarr to `out_path` = zarr not written, error given.
    - the `overwrite` argument is set to `True` and the user provides an empty directory to `out_path` = zarr written, no warning given.
    - the `overwrite` argument is set to `True` and the user provides a directory containing a zarr to `out_path` = zarr written, overwrite warning given.
I think we need something similar in place for `DatasetWrapper.from_files()`. 

**Documentation**
1. Would you be able to provide 2 examples of how this can be used in the `__init.py__` usage documentation please? I say two as I envisage 1 example could be it's simplest form, while another could demonstrate a bit more flexibility, optional arguments etc.
2. Thanks for updating relevant docstrings.

**Tests**
1. From looking at the fixtures used in `test_read_dataset_from_file`, is it just .tif files that are being tested? Demonstrating that .zarr files can be read in and resampled successfully would demonstrate more robustness in the code. Would it possible to use a fixture factory or similar to achieve this? 

Thinking pragmatically, I don't see an issue with `_reshape_raster` being quite a large and unwieldy internal function. I would much rather time was spent on usability focussed improvements given our time pressure at the moment. 

Let me know if you would like to discuss any of these things.

**Review by jpd-defra — CHANGES_REQUESTED** [review]
See comment above.

**Comment by jamesgyoung** [comment]
#### Usage
1. The warning was in the wrong place. It was being called after chunks was already used. I moved this.
2. I've added an explicit error if `out_path` is not provided but is needed.
3. I've moved your overwrite check from `DataFrameWrapper.to_zarr` into a function `_warn_zarr_overwrite` in `_dataframe.py`. I then use this same function in `DatsetWrapper.from_files` and have added an `overwrite` arg to the method

#### Documentation
1. I've added an example to accompany the existing one.

#### Tests
1. Yes just tifs. It would be possible to use zarrs, but I think we reasoned the opposite of zarrs being "more" robust, in that the mostly likely files that need to be resampled won't be zarrs at all, as the overwhelming majority of zarrs will be produced by the data model itself, where no resampling or reshaping needs to occur. I think addressing this should be a separate issue to write a fixture factory to test multiple file types like you have done with vector on the end to end test.

**Review by jamesgyoung — COMMENTED** [review]
@jpd-defra Changes submitted.

**Comment by jpd-defra** [comment]
Nice work. I've just run the code using Dan's example and it seems to work fine and the errors appear as expected regarding out_path presence and overwriting.

I agree about the separate issue for testing different input file types and will create one for the backlog. 

Good job!

**Review by jpd-defra — APPROVED** [review]

**Pull request merged**
