### PR TITLE
Draft aim and functionality for readme

### PR DESCRIPTION
**Pull request by danlewis85**
This is my view on the aim and functionality required of the data model.

@EFT-Defra to check you are happy
@DavidFouracreDEFRA and @alistairedwardes-eau to review and amend/improve to reach a common view on what this should be doing.

All other, for information, but comment if you wish (@jpd-defra, @JordanPinder-Defra, @lara56, @s-flint-defra, @JamesKeny0n, @PiumiA)

### CODE REVIEW

**Review by EFT-Defra — APPROVED** [review]
Looks good to me!

**Review by alistairedwardes-eau — COMMENTED** [review]
Findable 
Is there anything we can say about how to find the data beyond documenting it?
For example how do we register the documentation to make it findable? 

Interoperable
Do we want to say more about the semantic interoperability and types of dataset e.g. capability masks, and suitability surfaces?

Core components 
Can we say more about how the core components of relate to QFAIR?
How do we define what transformations are that need to be captured? 
I think the transformations need to relate to their potential to impact data quality, e.g. datatype conversion, reclassification, resampling, geometric transformation, coordinate transformation, etc.

Should "4. A specification" really be a target schema? So we can think of the process more in terms of data harmonisation?
We've previously discussed that in time we want to define set of classes for dataset types e.g. capability, suitability, …?

**Comment by danlewis85** [comment]
> Findable Is there anything we can say about how to find the data beyond documenting it? For example how do we register the documentation to make it findable?

I haven't specifically addressed this as I don't understand what you mean by 'register the documentation', are you talking about data catalogues, DOIs or something else?

In any case, I think this might be out of scope for the data model library, but happy to follow up if I'm mistaken.

**Comment by danlewis85** [comment]
> Interoperable
Do we want to say more about the semantic interoperability and types of dataset e.g. capability masks, and suitability surfaces?

I've added some thoughts on the semantic interoperability bit, but I'm not sure how valuable what I've added is to the readme document though. On the one hand I think the data model needs, in future, to add ways of labelling/annotating data according to an ontology, but I think that ontology needs to be developed elsewhere.

**Comment by danlewis85** [comment]
> Should "4. A specification" really be a target schema? So we can think of the process more in terms of data harmonisation?
We've previously discussed that in time we want to define set of classes for dataset types e.g. capability, suitability, …?

I've added target schema to the text to reflect that that's what I meant by specification.

I'm not entirely sure whether we want distinct classes to represent objects in our ontology versus an approach to annotating data with this information, so I haven't reflected that in the readme as yet. We need to discuss and agree how we might approach this.

**Comment by danlewis85** [comment]
> Core components
Can we say more about how the core components of relate to QFAIR?

I guess we could, but I'm not sure I really see the value in doing this in the readme, could you say more about why you think this would be important?

> How do we define what transformations are that need to be captured?

I've taken the view that all transformations need to be captured and reflected this in the readme.

> I think the transformations need to relate to their potential to impact data quality, e.g. datatype conversion, reclassification, resampling, geometric transformation, coordinate transformation, etc.

I agree that a subset of transformations need to be understood in this way, however it's not immediately apparent to me how we best implement this. I think a discussion is warranted.

**Comment by danlewis85** [comment]
I'd like to move that we commit to the revised readme - potentially with some minor amendments arising form the re-review, and then seek to distil some new issues from the questions that are unanswered, I think there are two key issues to surface:

1. How to capture quality-relevant transformations.
2. Developing an ontology relevant to data we're creating using the data model.

**Comment by EFT-Defra** [comment]
I'm not going to be able to re-review this until the next sprint anyway, so I think committing and capturing further changes in issues is a sensible approach.

**Pull request merged**
