### PR TITLE
Fix `flake8` linting

### LINKED ISSUE #111: fix flake8

### PR DESCRIPTION
**Pull request by EFT-Defra**
Closes #111 by:

- Updating `flake8`, `bandit`, and `flake8-bandit` 
- Restricting linting to `src/`, `tests/`, and `noxfile.py`

### CODE REVIEW

**Comment by EFT-Defra** [comment]
@jpd-defra just FYI

**Review by jpd-defra — APPROVED** [review]
Had a quick read up on tags, and from what I can tell they are a way to group together noxfile tasks - hoping i've understood that right...

**Comment by EFT-Defra** [comment]
This is now failing because `flake8` is finding issues, not because `flake8` itself is failing.

**Comment by EFT-Defra** [comment]
> Had a quick read up on tags, and from what I can tell they are a way to group together noxfile tasks - hoping i've understood that right...

Yes, that's right, this isn't necessary to get `flake8` working but I found I needed a way to run everything but `docs-build` locally and `tags` appear to be the answer!

**Pull request merged**
